### PR TITLE
do not account missing files

### PR DESCRIPTION
**Pull request by dvv**
This would help skipping editor lockfiles etc.
Please verify and consider applying

### CODE REVIEW

**Comment by probably-not** [comment]
Hi @dvv 
Can you please give a quick use case here and a test where this is happening?
It's been a while since I looked at this project, but from what I remember, this is explicitly looping over each file in each directory. What situation would cause there to be a file missing when we're looping explicitly over files?

**Comment by dvv** [comment]
Hi @probably-not 

It appeared when I was modifying files with mcedit: it put kinda lock file ending with `.ex` with quirk permission.
Remix saw these files in dir listing but could not read them and put errors in the console.

So whether it's a valid issue depends on text editor )

**Comment by probably-not** [comment]
Interesting... I've never heard of an editor doing that before... Putting a lock file with the `.ex` file extension in the folder tree? Do you know why it's an `.ex` file extension and not a `.lock` file extension (like typical lock files)? Any documentation regarding this behaviour anywhere?

Can you get a snapshot of the folder/files that Remix is seeing and the permissions set on each of them?

Also provide a step by step example with some extra details here? I want to see whether I can recreate this locally (or within a container/vm, I don't think my current setup has mc or mcedit on it) somehow.

**Comment by probably-not** [comment]
@dvv I'm closing this as stale (it's been about 60 days without activity). If you'd like to reopen you can.

**Pull request closed without merging**
